// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUsDsHtmbQrNOIuyl9Mr_zARl3rLGK34',
    appId: '1:231030944816:web:06c12e4f57a808a426e9f5',
    messagingSenderId: '231030944816',
    projectId: 'ebase-3f858',
    authDomain: 'ebase-3f858.firebaseapp.com',
    databaseURL: 'https://ebase-3f858-default-rtdb.firebaseio.com',
    storageBucket: 'ebase-3f858.appspot.com',
    measurementId: 'G-LJYCE6MYMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZB39s8O_TjIgqVsKH_J1zmaRgRMbhSIk',
    appId: '1:231030944816:android:96dff2613b19de3426e9f5',
    messagingSenderId: '231030944816',
    projectId: 'ebase-3f858',
    databaseURL: 'https://ebase-3f858-default-rtdb.firebaseio.com',
    storageBucket: 'ebase-3f858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOHL_2zoRlLqWD_z0xoe_ZRiGLCLgrEQ',
    appId: '1:231030944816:ios:ddfa2df64b3bc28226e9f5',
    messagingSenderId: '231030944816',
    projectId: 'ebase-3f858',
    databaseURL: 'https://ebase-3f858-default-rtdb.firebaseio.com',
    storageBucket: 'ebase-3f858.appspot.com',
    iosClientId: '231030944816-0ev12n0mddk7qf7k7mkk3ukq05ofjvmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingnotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXOHL_2zoRlLqWD_z0xoe_ZRiGLCLgrEQ',
    appId: '1:231030944816:ios:ddfa2df64b3bc28226e9f5',
    messagingSenderId: '231030944816',
    projectId: 'ebase-3f858',
    databaseURL: 'https://ebase-3f858-default-rtdb.firebaseio.com',
    storageBucket: 'ebase-3f858.appspot.com',
    iosClientId: '231030944816-0ev12n0mddk7qf7k7mkk3ukq05ofjvmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingnotifications',
  );
}
